# Generated by Django 5.1.7 on 2025-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsuser",
            name="email",
            field=models.EmailField(
                help_text="Укажите вашу почту", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customsuser",
            name="first_name",
            field=models.CharField(help_text="Укажите ваше имя", max_length=30),
        ),
        migrations.AlterField(
            model_name="customsuser",
            name="last_name",
            field=models.CharField(help_text="Укажите вашу фамилию", max_length=30),
        ),
        migrations.AlterField(
            model_name="customsuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Укажите ваш номер телефона",
                max_length=15,
                null=True,
            ),
        ),
    ]
