# Generated by Django 5.1.7 on 2025-03-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Наименование категории",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Наименование подкатегории",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "подкатегории",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "image_small",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/small/",
                        verbose_name="Маленькое изображение",
                    ),
                ),
                (
                    "image_medium",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/medium/",
                        verbose_name="Среднее изображение",
                    ),
                ),
                (
                    "image_large",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/large/",
                        verbose_name="Большое изображение",
                    ),
                ),
                ("price", models.FloatField(help_text="Введите стоимость продукта")),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Податегории",
                        to="catalog.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["title"],
            },
        ),
    ]
